### ISSUE TITLE
用的是EasyWeChat 的 5.x版本

### ISSUE THREAD

**Issue by lbk0930** [hpyer/node-easywechat-demo#1]
const response = await app.app_code.getUnlimit(id, {
            page: 'pages/detail/detail',
            width: 600,
        });
        这个输出偶尔不正确，报40001，但是我的appid，与secret没有问题，因为是突然报出

**Comment by hpyer** [comment]
看了下文档，40001错误的说明是 `获取 access_token 时 AppSecret 错误，或者 access_token 无效。请开发者认真比对 AppSecret 的正确性，或查看是否正在为恰当的公众号调用接口` 

你可以看下调用的时候 access_token 是否过期了

https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/qrcode-link/qr-code/getUnlimitedQRCode.html#%E9%94%99%E8%AF%AF%E7%A0%81

**Comment by lbk0930** [comment]
// 小程序配置
{
  // appId
  app_id: 'your-app-id',
  // appSecret
  secret: 'your-app-secret'
}确实应该是过期了，但是这个只有这两配置项，那么只要这两配置没问题，MiniProgram是不是会自动获取token，?我的配置是没有问题的，因为刚才又好了几分钟，然后又不行了，我什么都没改，这个接口只是在后台生成，跟前台没有关系

**Comment by hpyer** [comment]
1、首先，了解下微信的 access_token 的机制，你就可以知道 access_token 的有效期只有7200秒，也就是2小时。这就是导致你为什么刚开始可以，后面又不可以的原因。官方文档：https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/mp-access-token/getAccessToken.html

2、在第一次请求的时候，因为 EasyWeChat 获取不到 access_token 会自动尝试获取一次。但是2小时后，这个 access_token 就过期了，这时微信就会报错，而 EasyWeChat 并不会去处理接口错误。

3、解决办法是，在服务端单独启一个定时任务，在 access_token 过期前，调用 `app.access_token.getToken(true);` 去刷新 access_token，已保证每次使用的都是有效的 access_token
